### ISSUE TITLE
Error upgrading from collective.workspace 1.3

### ISSUE THREAD

**Issue by ale-rt** [collective/collective.workspace#25]
```
Traceback (most recent call last):
  File "/home/ale/.buildout/eggs/Zope2-2.13.26-py2.7.egg/ZPublisher/Publish.py", line 138, in publish
    request, bind=1)
  File "/home/ale/.buildout/eggs/Zope2-2.13.26-py2.7.egg/ZPublisher/mapply.py", line 77, in mapply
    if debug is not None: return debug(object,args,context)
  File "/home/ale/.buildout/eggs/Zope2-2.13.26-py2.7.egg/ZPublisher/Publish.py", line 48, in call_object
    result=apply(object,args) # Type s<cr> to step into published object.
  File "/home/ale/.buildout/eggs/Products.GenericSetup-1.8.8-py2.7.egg/Products/GenericSetup/tool.py", line 1053, in manage_doUpgrades
    step.doStep(self)
  File "/home/ale/.buildout/eggs/Products.GenericSetup-1.8.8-py2.7.egg/Products/GenericSetup/upgrade.py", line 166, in doStep
    self.handler(tool)
  File "/home/ale/.buildout/eggs/collective.workspace-2.0b1-py2.7.egg/collective/workspace/setuphandlers.py", line 47, in migrate_groups
    (m.groups | set([u'Members'])) &
TypeError: unsupported operand type(s) for |: 'NoneType' and 'set'
```

**Comment by ale-rt** [comment]
I have a patch for this one.
The problem is that here: https://github.com/collective/collective.workspace/blob/master/src/collective/workspace/membership.py#L128
`self.__dict__.get('groups', set())` was returning a list that has no attribute copy:
```
>>> [].copy()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'list' object has no attribute 'copy'
>>> set([]).copy()
set([])
```

**Comment by ale-rt** [comment]
Closed because I mistakenly pushed to master... Sorry
