### ISSUE TITLE
RuntimeError: Mutable property provider shadowed by read only provider

### ISSUE THREAD

**Issue by maartenkling** [collective/collective.workspace#6]
@davisagli  when using your branch and starting robottests
plone 4.1.4

Traceback (most recent call last):
  File "./bin/robot-server", line 457, in <module>
    sys.exit(plone.app.robotframework.server.server())
  File "/Users/kekjo/.buildout/eggs/plone.app.robotframework-0.9.8-py2.7.egg/plone/app/robotframework/server.py", line 174, in server
    start(args.layer)
  File "/Users/kekjo/.buildout/eggs/plone.app.robotframework-0.9.8-py2.7.egg/plone/app/robotframework/server.py", line 42, in start
    zsl.start_zope_server(zope_layer_dotted_name)
  File "/Users/kekjo/.buildout/eggs/plone.app.robotframework-0.9.8-py2.7.egg/plone/app/robotframework/server.py", line 221, in start_zope_server
    setup_layer(new_layer)
  File "/Users/kekjo/.buildout/eggs/plone.app.robotframework-0.9.8-py2.7.egg/plone/app/robotframework/server.py", line 291, in setup_layer
    setup_layer(base, setup_layers)
  File "/Users/kekjo/.buildout/eggs/plone.app.robotframework-0.9.8-py2.7.egg/plone/app/robotframework/server.py", line 300, in setup_layer
    layer.setUp()
  File "/Users/kekjo/.buildout/eggs/plone.app.testing-4.0.2-py2.7.egg/plone/app/testing/helpers.py", line 343, in setUp
    self.setUpPloneSite(portal)
  File "/Users/kekjo/opt/kekjosomething.buildout.groups/src/kekjoportal.contenttypes/kekjoportal/contenttypes/testing.py", line 1067, in setUpPloneSite
    self._createDistrict(portal, 'District', '100')
  File "/Users/kekjo/opt/kekjosomething.buildout.groups/src/kekjoportal.contenttypes/kekjoportal/contenttypes/testing.py", line 555, in _createDistrict
    df[id_].processForm()
  File "/Users/kekjo/.buildout/eggs/Products.Archetypes-1.7.12-py2.7.egg/Products/Archetypes/BaseObject.py", line 665, in processForm
    event.notify(ObjectInitializedEvent(self))
  File "/Users/kekjo/.buildout/eggs/zope.event-3.5.1-py2.7.egg/zope/event/__init__.py", line 31, in notify
    subscriber(event)
  File "/Users/kekjo/.buildout/eggs/zope.component-3.9.5-py2.7.egg/zope/component/event.py", line 24, in dispatch
    zope.component.subscribers(event, None)
  File "/Users/kekjo/.buildout/eggs/zope.component-3.9.5-py2.7.egg/zope/component/_api.py", line 136, in subscribers
    return sitemanager.subscribers(objects, interface)
  File "/Users/kekjo/.buildout/eggs/zope.component-3.9.5-py2.7.egg/zope/component/registry.py", line 321, in subscribers
    return self.adapters.subscribers(objects, provided)
  File "/Users/kekjo/.buildout/eggs/zope.interface-3.6.7-py2.7-macosx-10.10-x86_64.egg/zope/interface/adapter.py", line 585, in subscribers
    subscription(*objects)
  File "/Users/kekjo/.buildout/eggs/zope.component-3.9.5-py2.7.egg/zope/component/event.py", line 32, in objectEventNotify
    zope.component.subscribers((event.object, event), None)
  File "/Users/kekjo/.buildout/eggs/zope.component-3.9.5-py2.7.egg/zope/component/_api.py", line 136, in subscribers
    return sitemanager.subscribers(objects, interface)
  File "/Users/kekjo/.buildout/eggs/zope.component-3.9.5-py2.7.egg/zope/component/registry.py", line 321, in subscribers
    return self.adapters.subscribers(objects, provided)
  File "/Users/kekjo/.buildout/eggs/zope.interface-3.6.7-py2.7-macosx-10.10-x86_64.egg/zope/interface/adapter.py", line 585, in subscribers
    subscription(*objects)
  File "/Users/kekjo/opt/kekjosomething.buildout.groups/src/collective.workspace/src/collective/workspace/workspace.py", line 158, in handle_workspace_modified
    group.setProperties(title=group_title)
  File "/Users/kekjo/.buildout/eggs/Products.PlonePAS-4.0.11-py2.7.egg/Products/PlonePAS/tools/groupdata.py", line 281, in setProperties
    return self.setGroupProperties(properties)
  File "/Users/kekjo/.buildout/eggs/Products.PlonePAS-4.0.11-py2.7.egg/Products/PlonePAS/tools/groupdata.py", line 317, in setGroupProperties
    raise RuntimeError, ("Mutable property provider "
RuntimeError: Mutable property provider shadowed by read only provider

**Comment by davisagli** [comment]
@maartenkling what order are the PAS property plugins in?

**Comment by maartenkling** [comment]
@davisagli don't know just normal robotserver startup nothing configured

**Comment by davisagli** [comment]
Well, the robot test for collective.workspace itself succeeds, so I suspect something in your project may be changing the default plugins. Can you add a Pause to your robot test, go into acl_users and tell me what list of plugins it has?

**Comment by maartenkling** [comment]
ah well found it, someone added something to setuphandlers
